#!/bin/bash

ToDir="../src/main/resources/translations"
for i in *.properties;
do
    printf "$i\n"
    native2ascii -encoding utf8 $i "${ToDir}"/$i
done



printf "\n\nAfter the conversion, we need to check the converted files in /src/main/resources/translations\n"
printf 'we will search for "\\u00a0", using "grep u00a0 program*"\n\n'

printf "Now grepping for the incorrect characters. If nothing is returned you are good to go.\n\n"
cd ${ToDir}
grep u00a0 program*


